# Site settings
title: Edgar Velazquez Website
description: Personal Portfolio
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Edgar Velazquez
user_description: Passionate about Computer Science. International Student studying Computer Science at San Jose State University graduating in December 2020. I like to code, cook, and exercise in my free time. I enjoy solvingLeetCode problems just for fun. I am looking for a fulltime software developer position for Spring 2020
user_skills: Java, C++, Python, SQL, NoSQL, XML, HTML, CSS, Javascript
user_title: Software Developer
email: edgar.ra.velazquez@gmail.com
github_username:  edgarvelazquez


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
